name: PR Review with Dify
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Collect PR Data
        id: pr_data
        shell: bash
        run: |
          echo "Collecting PR data..."
          
          # Get files changed
          FILES_CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tr '\n' ', ')
          
          # Create and escape query
          QUERY_TEXT="Review PR: ${{ github.event.pull_request.title }} with changes in files: ${FILES_CHANGED}"
          QUERY_ESCAPED=$(echo "$QUERY_TEXT" | jq -Rsc .)
          echo "query=${QUERY_ESCAPED}" >> $GITHUB_OUTPUT

      - name: Send to Dify
        id: dify_request
        shell: bash
        run: |
          echo "Sending request to Dify..."
          
          # Prepare JSON data with an empty conversation_id
          JSON_DATA=$(cat <<EOF
          {
            "inputs": {},
            "query": ${{ steps.pr_data.outputs.query }},
            "response_mode": "streaming",
            "conversation_id": "",
            "user": "github"
          }
          EOF
          )
          
          # Send request and handle streaming response
          RESPONSE_BODY=""
          RESPONSE=$(curl -s -N -X POST \
            -H "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "$JSON_DATA" \
            "https://verf.io/v1/chat-messages")

          # Read the response line by line
          while IFS= read -r line; do
            # Append each line to the RESPONSE_BODY
            RESPONSE_BODY+="$line"
          done <<< "$RESPONSE"

          # Output the complete response
          echo "Complete Response: $RESPONSE_BODY"
          
          # Check if the response is valid and handle it
          if [[ -n "$RESPONSE_BODY" ]]; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "$RESPONSE_BODY" > response.json
          else
            echo "status=error" >> $GITHUB_OUTPUT
            echo "error_message=No response received." >> $GITHUB_OUTPUT
          fi

      - name: Post Review Comment
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            
            try {
              let commentBody;
              
              // Read the response data
              const responseData = fs.readFileSync('response.json', 'utf8');
              console.log('Response Data:', responseData); // Debugging statement

              // Attempt to parse the response
              const response = JSON.parse(responseData);
              
              if ('${{ steps.dify_request.outputs.status }}' === 'success') {
                commentBody = response.answer || response.text || 'No review content provided';
              } else {
                commentBody = '⚠️ Error: Failed to generate review.\nError: ${{ steps.dify_request.outputs.error_message }}';
              }
              
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.name,
                body: commentBody
              });
            } catch (error) {
              console.error('Error:', error);
              throw error;
            }
