name: PR Review with Dify
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Dify
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          RESPONSE=$(curl -s -X POST "https://verf.io/v1/chat-messages" \
            -H "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"inputs\": {},
              \"query\": \"Review PR: $PR_TITLE\",
              \"response_mode\": \"streaming\",
              \"conversation_id\": \"pr_$PR_NUMBER\",
              \"user\": \"github\"
            }")
          
          echo "$RESPONSE" > response.json
          
          if jq -e . >/dev/null 2>&1 <<<"$RESPONSE"; then
            COMMENT_BODY=$(jq -r '.answer // .text // "No review provided"' response.json)
          else
            COMMENT_BODY="Error: Invalid response from API"
          fi
          
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments" \
            -d "{\"body\":\"$COMMENT_BODY\"}"
